server:
    port: 9082

spring:
    #添加RabbitMQ的配置
    rabbitmq:
      host: 118.190.40.58
      port: 5672
      username: guest
      password: guest
       #支持发布确定
      publisher-confirms: true
      #支持发布返回
      publisher-returns: true
      listener:
        simple:
          #采用手动应答
          acknowledge-mode: manual
          #当前监听容器数
          concurrency: 1
          #最大数
          max-concurrency: 1
          #是否支持重试
          retry:
            enabled: true






